simple1:
	nvcc simple1.cu -o simple1.o

simple2: 
	nvcc simple2.cu -o simple2.o

identify:
	nvcc identify.cu -o identify.o

identify_naive1:
	nvcc identify_naive1.cu -o identify_naive1.o

identify_naive2:
	nvcc identify_naive2.cu -o identify_naive2.o

clean:
	rm *.o

